### ISSUE TITLE
Unknown custom element: <trix-editor> 

### ISSUE THREAD

**Issue by mwangaben** [Dymantic/vue-trix-editor#3]
Please help to resolve this issue on the console, 
When I use below code n due file, everything went well but I get an error in console

    <template>
    <div>
        <p>Working</p>
        <trix-vue v-model="body"></trix-vue>
    </div>
    </template>

     <script>
        import TrixVue from '@dymantic/vue-trix-editor';
        export default {
           data(){
            return {
                body: 'Helo'
            }
        },
        components: {TrixVue}
       }
      </script>

      <style scoped>

      </style>

**_console Errol_**

        [Error] [Vue warn]: Unknown custom element: <trix-editor> - did you register the component         correctly? For recursive components, make sure to provide the "name" option.

found in

---> <TrixVue> at TrixVueWysiwyg.vue
       <MyTrix> at resources/js/components/Sandbox/MyTrix.vue
         <Root>
	warn (app.js:38582)
	createElm (app.js:43557)
	createChildren (app.js:43671)
	createElm (app.js:43573)
	patch (app.js:44080)
	_update (app.js:40649)
	updateComponent (app.js:40777)
	get (app.js:41131)
	Watcher (app.js:41120)
	mountComponent (app.js:40784)
	init (app.js:42126)
	createComponent (app.js:43597)
	createElm (app.js:43544)
	createChildren (app.js:43671)
	createElm (app.js:43573)
	patch (app.js:44080)
	_update (app.js:40649)
	updateComponent (app.js:40777)
	get (app.js:41131)
	Watcher (app.js:41120)
	mountComponent (app.js:40784)
	init (app.js:42126)
	createComponent (app.js:43597)
	createElm (app.js:43544)
	createChildren (app.js:43671)
	createElm (app.js:43573)
	createChildren (app.js:43671)
	createElm (app.js:43573)
	createChildren (app.js:43671)
	createElm (app.js:43573)
	patch (app.js:44119)
	_update (app.js:40649)
	updateComponent (app.js:40777)
	get (app.js:41131)
	Watcher (app.js:41120)
	mountComponent (app.js:40784)
	_init (app.js:42629)
	Vue (app.js:42718)
	(anonymous function) (app.js:63770)
	__webpack_require__ (app.js:20)
	(anonymous function) (app.js:63687)
	__webpack_require__ (app.js:20)
	(anonymous function) (app.js:63)
	Global Code (app.js:64)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (favicon.ico, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (TrixVue.umd.js.map, line 0)

**Comment by michaeljoyner** [comment]
I agree that this is a fairly annoying warning to get in the console, but I am not sure if it can easily be fixed my end, but I am very open to suggestions. I can't just use the `v-pre` tag, as Vue still needs to be aware of the element, even though it is not a Vue element.

Note that if you use Vue in "production mode", this warning will not appear, it only shows in "development mode". [Here are the docs](https://vuejs.org/v2/guide/deployment.html) for development/production if you need.

Another option you have is to add the trix-editor to Vue's ignored elements. You would need to add the following to your code:

```javascript
Vue.config.ignoredElements = [
    'trix-editor',
];
``` 
The docs for this are [here](https://vuejs.org/v2/api/#ignoredElements).

**Comment by mwangaben** [comment]
Thanks  a million @michaeljoyner , I think I will go the route you have suggested,

**Comment by michaeljoyner** [comment]
Glad to help. I will add a note to the readme when I get a chance.
