### ISSUE TITLE
Alt Attributes needed

### ISSUE THREAD

**Issue by successdavis** [Dymantic/vue-trix-editor#6]
The plugin is working fine but there is no support for alt attributes

**Comment by michaeljoyner** [comment]
Hi @successdavis, can you describe a little more in detail what you need and I'll do my best to try help.

**Comment by successdavis** [comment]
I need some way to set the alt attribute for my images 

<img src="" alt="">

I can't find any documentation on how to include the alt to the image I attached to my editor. Is there a way around this?

**Comment by michaeljoyner** [comment]
I see. It would be a useful addition, but it may take me a couple of days to get done. It is fairly late in the day here, I will look more into this in the morning.

**Comment by michaeljoyner** [comment]
To allow for the adding of the alt attribute for images, the UI will have to change. The add image button can no longer directly bring up your file selector, but it will have to bring up some kind of dialog that allows you to select a file, as well as enter your alt text. Seeing as the alt text is quite important on images, I will get started on this soon.

**Comment by michaeljoyner** [comment]
Okay, this is done. If you upgrade to v0.3.0, you will be able to use the `:insert-images-with-dialog="true"` prop to get what you want. You can see the section in the readme [here](https://github.com/Dymantic/vue-trix-editor#adding-alt-attributes-for-your-images).

Let me know what issues you have, and whether I can close this issue. Thanks.
