### ISSUE TITLE
custom axios

### ISSUE THREAD

**Issue by pestev** [Dymantic/vue-trix-editor#7]
package is great, but i am missing to custom axios. I need change baseUrl and token, can't find solution for this.

**Comment by michaeljoyner** [comment]
Hi @pestev, thanks. I will have to look into this and see what can be done. Do you have any ideas of how you'd implement this?

**Comment by pestev** [comment]
there can be saved event, but then package cant react on success / error saving.
Mayby using props. Pass axios instance, or saving closure/promise.
`saveContent() {
    ...
      axiosProps
        .post(this.savePath, content)
        .then(() => {
        })
 ...
},`
or
`saveContent() {
    ...
      savingMethodProps
        .then(() => {
        })
 ...
},`

**Comment by michaeljoyner** [comment]
Would your issue be resolved if a prop was added which would be then passed to axios as config when making the post request to save or upload image?

**Comment by pestev** [comment]
yes, that should work. Thank You :)

**Comment by michaeljoyner** [comment]
Great! I'll get to it as soon as possible, but most likely only tomorrow morning.

**Comment by michaeljoyner** [comment]
If you upgrade to v0.4.0 you should be able to pas in your custom axios config as a prop. Please let me know if you run into any issues. Thanks.
