### ISSUE TITLE
How do I upload an attachment to the server when I attach it in the trix-editor

### ISSUE THREAD

**Issue by abrhambas01** [Dymantic/vue-trix-editor#8]
That's how the trix-editor does it right ? I have to upload an attachment to the server once the attachment is attached in the editor ?  it should have it like this righ t?
```
imageAttached(file){
			console.log("image attached",file);
```

**Comment by michaeljoyner** [comment]
Hi @abrhambas01. What kind of attachment would you like to attach? There are props available to handle image uploads for you. If you have another kind of attachment the process is a little different.

**Comment by abrhambas01** [comment]
image attachments @michaeljoyner

**Comment by michaeljoyner** [comment]
If you are attaching an image, you can do it as per the instructions [in this section of the readme](https://github.com/Dymantic/vue-trix-editor#uploading-images), where you pass in the endpoint you would like the image to be uploaded to, and then the component will upload it for you.

If you are building out your own UI for the image upload, as [described here](https://github.com/Dymantic/vue-trix-editor#extending-functionality-through-scoped-slot), you would do the upload yourself however you chose, then pass the final html you would like as the attachment to the attachment method described in the readme section linked above.

I hope that is helpful, if not, let me know. Thanks.
